Imports System.Data
Imports System.Data.SqlClient
Module Variables_Ventanas
    'VARAIBLES VISTA MAESTRO DE USUARIOS (INICIOS DE SESION)
    Public isuID_USUARIO As Integer
    Public isuID_TIPO_USUARIO As Integer
    Public isuD_TIPO_USUARIO As String
    Public isuUSUARIO As String
    Public isuUSUARIO_R As Integer      'CONDICION PARA REPORTES
    Public isuCUENTA As String
    Public isuCLAVE As String
    Public isuID_SESION_USUARIO As Integer
    Public isuD_SESION_USUARIO As String
    Public isuID_ESTADO_USUARIO As Integer
    Public isuD_ESTADO_USUARIO As String
    Public isuCODIGO As String
    Public isuCARGO As String
    Public isuDEPARTAMENTO As String
    Public isuSERVICIO As String
    Public isuN1 As String
    Public isuN2 As String
    Public isuN3 As String
    Public isuN4 As String
    Public isuN5 As String
    Public isuN6 As String
    Public isuN7 As String
    Public isuN8 As String
    Public isuFECHA_ALTA As String
    Public isuUSUARIO_EJECUTA_ALTA As String
    Public isuTERMINAL_ALTA As String
    Public isuIP_ALTA As String
    Public isuFECHA_BAJA As String
    Public isuUSUARIO_EJECUTA_BAJA As String
    Public isuTERMINAL_BAJA As String
    Public isuIP_BAJA As String
    Public isuID_ESTADO_R As Integer
    'VARAIBLES VISTA MAESTRO DE USUARIOS
    Public uID_USUARIO As Integer
    Public uID_TIPO_USUARIO As Integer
    Public uD_TIPO_USUARIO As String
    Public uUSUARIO As String
    Public uCUENTA As String
    Public uCLAVE As String
    Public uID_SESION_USUARIO As Integer
    Public uD_SESION_USUARIO As String
    Public uID_ESTADO_USUARIO As Integer
    Public uD_ESTADO_USUARIO As String
    Public uCODIGO As String
    Public uCARGO As String
    Public uNIVEL1 As String
    Public uNIVEL2 As String
    Public uNIVEL3 As String
    Public uNIVEL4 As String
    Public uNIVEL5 As String
    Public uNIVEL6 As String
    Public uNIVEL7 As String
    Public uNIVEL8 As String
    Public uFECHA_ALTA As String
    Public uUSUARIO_EJECUTA_ALTA As String
    Public uTERMINAL_ALTA As String
    Public uIP_ALTA As String
    Public uFECHA_BAJA As String
    Public uUSUARIO_EJECUTA_BAJA As String
    Public uTERMINAL_BAJA As String
    Public uIP_BAJA As String
    Public uID_ESTADO_R As Integer
    'VISTA MAESTRO DE CARGOS SIT

    Public vmcsID_M_Ct As Integer    '*
    Public vmcsORDENt As String      '*

    Public vmcsID_M_C As Integer
    Public vmcsORDEN As String
    Public vmcsID_N1 As Integer
    Public vmcsORDEN_N1 As String
    Public vmcsD_N1 As String
    Public vmcsID_N2 As Integer
    Public vmcsORDEN_N2 As String
    Public vmcsD_N2 As String
    Public vmcsID_N3 As Integer
    Public vmcsORDEN_N3 As String
    Public vmcsD_N3 As String
    Public vmcsID_N4 As Integer
    Public vmcsORDEN_N4 As String
    Public vmcsD_N4 As String
    Public vmcsID_N5 As Integer
    Public vmcsORDEN_N5 As String
    Public vmcsD_N5 As String
    Public vmcsID_N6 As Integer
    Public vmcsORDEN_N6 As String
    Public vmcsD_N6 As String
    Public vmcsID_N7 As Integer
    Public vmcsORDEN_N7 As String
    Public vmcsD_N7 As String
    Public vmcsID_N8 As Integer
    Public vmcsORDEN_N8 As String
    Public vmcsD_N8 As String
    Public vmcsID_T_ES As Integer
    Public vmcsD_T_ES As String
    Public vmcsN_ORDEN_MIXTA As String
    Public vmcsN_ORDEN_MILITAR As String
    Public vmcsN_ORDEN_PAME As String
    Public vmcsID_CARGO_ES As Integer
    Public vmcsD_CARGO_ES As String
    Public vmcsID_GP As Integer
    Public vmcsD_GP As String
    Public vmcsID_GR As Integer
    Public vmcsD_GR As String
    Public vmcsID_CAT_SALARIAL As Integer
    Public vmcsD_CAT_SALARIAL As String
    Public vmcsID_M_P As Integer
    Public vmcsCODIGO As String
    Public vmcsAN As String
    Public vmcsNA As String
    Public vmcsID_SITUACION As Integer
    Public vmcsD_SITUACION As String
    Public vmcsJEFE As Boolean
    Public vmcsMIXTA As Boolean
    Public vmcsMILITAR As Boolean
    Public vmcsPAME As Boolean
    Public vmcsID_ESTABLECIMIENTO As Integer
    Public vmcsD_ESTABLECIMIENTO As String
    'VISTA MAESTRO DE CARGOS SIT (TRASLADOS)
    Public TvmcsID_M_C As Integer
    Public TvmcsORDEN As String
    Public TvmcsID_N1 As Integer
    Public TvmcsORDEN_N1 As String
    Public TvmcsD_N1 As String
    Public TvmcsID_N2 As Integer
    Public TvmcsORDEN_N2 As String
    Public TvmcsD_N2 As String
    Public TvmcsID_T_ES As Integer
    Public TvmcsD_T_ES As String
    Public TvmcsN_ORDEN_MIXTA As String
    Public TvmcsN_ORDEN_MILITAR As String
    Public TvmcsN_ORDEN_PAME As String
    Public TvmcsID_CARGO_ES As Integer
    Public TvmcsD_CARGO_ES As String
    Public TvmcsID_GP As Integer
    Public TvmcsD_GP As String
    Public TvmcsID_GR As Integer
    Public TvmcsD_GR As String
    Public TvmcsID_CAT_SALARIAL As Integer
    Public TvmcsD_CAT_SALARIAL As String
    Public TvmcsID_M_P As Integer
    Public TvmcsCODIGO As String
    Public TvmcsAN As String
    Public TvmcsID_SITUACION As Integer
    Public TvmcsD_SITUACION As String
    Public TvmcsJEFE As Boolean
    Public TvmcsMIXTA As Boolean
    Public TvmcsMILITAR As Boolean
    Public TvmcsPAME As Boolean
    'SPYC_VISTA MAESTRO DE CARGOS
    Public iID_M_C As Integer
    Public iID_M_P As Integer
    'SPYC_MAESTRO DE PERSONAS
    Public i_mp_ID_M_P As Integer
    Public i_mp_FEC_NAC As String
    Public i_mp_FEC_ING_PAME As String
    Public i_mp_FEC_ING_EN As String
    Public i_mp_CODIGO As String
    Public i_mp_APELLIDOS As String
    Public i_mp_NOMBRES As String
    Public i_mp_ID_T_SEXO As Integer
    Public i_mp_DIRECCION_1 As String
    Public i_mp_DIRECCION_2 As String
    Public i_mp_NSS As String
    Public i_mp_N_CEDULA As String
    Public i_mp_N_LIC As String
    Public i_mp_N_MINSA As String
    Public i_mp_LIC_IMAGEN As String
    Public i_mp_TELEFONO_1 As String
    Public i_mp_TELEFONO_2 As String
    Public i_mp_CONVENCIONAL As String
    Public i_mp_CORREO_1 As String
    Public i_mp_CORREO_2 As String
    Public i_mp_WHATSAPP As String
    Public i_mp_FACEBOOK As String
    Public i_mp_TWITTER As String
    Public i_mp_PESO As String
    Public i_mp_ESTATURA As String
    Public i_mp_ID_TEZ As Integer
    Public i_mp_ID_CABELLO As Integer
    Public i_mp_ID_N_ACADEMICO As Integer
    Public i_mp_ID_N_PROFESIONAL As Integer
    Public i_mp_ID_NACIONALIDAD_N As Integer
    Public i_mp_ID_DPTO_N As Integer
    Public i_mp_ID_M_N As Integer
    Public i_mp_LUGAR_N As String
    Public i_mp_ID_NACIONALIDAD_D As Integer
    Public i_mp_ID_DPTO_D As Integer
    Public i_mp_ID_M_D As Integer
    Public i_mp_LUGAR_D As String
    Public i_mp_ID_E_CIVIL As Integer
    Public i_mp_ID_T_HORARIO As Integer
    Public i_mp_N_C_BANCO As String
    Public i_mp_EMPLEADO_ANT As String
    Public i_mp_ID_T_AFILIACION As Integer
    Public i_mp_ID_T_PLAZA As Integer
    Public i_mp_D_N1 As String
    Public i_mp_D_N2 As String
    Public i_mp_FOTO        '***
    Public i_mp_ID_ESTADO_P As Integer
    Public i_mp_BECADO As String
    Public i_mp_ID_C_LIC As Integer
    Public i_mp_ID_T_SANGUINEO As Integer
    Public i_mp_OBSERVACIONES As String
    Public i_mp_ID_IPSS As Integer
    Public i_mp_ESPECIALISTA As String
    Public i_mp_SUBESPECIALISTA As String
    Public i_mp_ID_F As Integer
    Public i_mp_EN_SITUACION As String
    Public i_mp_CARGO_REAL As String
    Public i_mp_JEFE_REAL As String
    Public i_mp_CALCULO_VACACIONAL As String
    Public i_mp_ID_N_COMPETENCIA As Integer
    Public i_mp_SERVICIOS_PROFESIONALES As String
    Public i_mp_ID_ADMIN As Integer
    Public i_mp_D_ADMIN As String
    'SPYC_MAESTRO DE CARGOS
    Public i_mc_ID_M_C As Integer
    Public i_mc_ORDEN As String
    Public i_mc_ID_N1 As Integer
    Public i_mc_ID_N2 As Integer
    Public i_mc_ID_N3 As Integer
    Public i_mc_ID_N4 As Integer
    Public i_mc_ID_N5 As Integer
    Public i_mc_ID_N6 As Integer
    Public i_mc_ID_N7 As Integer
    Public i_mc_ID_N8 As Integer
    Public i_mc_ID_T_ES As Integer
    Public i_mc_N_ORDEN_MIXTA As String
    Public i_mc_N_ORDEN_MILITAR As String
    Public i_mc_N_ORDEN_PAME As String
    Public i_mc_ID_CARGO_ES As Integer
    Public i_mc_ID_GP As Integer
    Public i_mc_ID_GR As Integer
    Public i_mc_ID_CAT_SALARIAL As Integer
    Public i_mc_ID_M_P As Integer
    Public i_mc_ID_SITUACION As Integer
    Public i_mc_JEFE As Boolean
    Public i_mc_MIXTA As Boolean
    Public i_mc_MILITAR As Boolean
    Public i_mc_PAME As Boolean
    'VISTA MAESTRO DE MEDICOS ACREDITADOS
    Public vMAc_ID_MA As Integer
    Public vMAc_APELLIDOS As String
    Public vMAc_NOMBRES As String
    Public vMAc_ID_E_MED As Integer
    Public vMAc_D_E_MED As String
    Public vMAc_N_CEDULA As String
    Public vMAc_N_MINSA As String
    Public vMAc_TELEFONO_1 As String
    Public vMAc_TELEFONO_2 As String
    Public vMAc_CORREO_1 As String
    Public vMAc_CORREO_2 As String
    Public vMAc_ID_NACIONALIDAD_D As Integer
    Public vMAc_D_NACIONALIDAD_D As String
    Public vMAc_DIRECCION_D As String
    Public vMAc_ID_T_SEXO As Integer
    Public vMAc_D_T_SEXO As String
    Public vMAc_FEC_NAC As String
    Public vMAc_FEC_DESDE As String
    Public vMAc_FEC_HASTA As String
    Public vMAc_FACEBOOK As String
    Public vMAc_TWITTER As String
    Public vMAc_WHATSAPP As String
    Public vMAc_OBSERVACIONES As String
    'VISTA SOL_MAESTRO DE SOLICITANTES
    Public aspID_S As Integer
    Public aspCEDULA As String
    Public aspAPELLIDOS As String
    Public aspNOMBRES As String
    Public aspAN As String
    Public aspFECHA_NAC As String
    Public aspPERFIL As String
    Public aspID_T_SEXO As Integer
    Public aspD_T_SEXO As String
    Public aspDIRECCION_1 As String
    Public aspDIRECCION_2 As String
    Public aspTELEFONO_1 As String
    Public aspTELEFONO_2 As String
    Public aspCORREO_1 As String
    Public aspCORREO_2 As String
    Public aspWHATSAPP As String
    Public aspPADRE As String
    Public aspMADRE As String
    Public aspREFERENCIA_ACADEMICA As String
    Public aspREFERENCIA_ESTUDIOS As String
    Public aspRECOMENDADO_POR As String
    Public aspOBSERVACIONES As String
    Public aspID_ESTADO_R As Integer
    Public aspFECHA_I As String
    'VISTA SOL_MAESTRO DE SOLICITANTES PROCESOS
    Public asppID_S_P As Integer
    Public asppID_S As Integer
    Public asppFECHA_P As String
    Public asppID_PROC As Integer
    Public asppD_PROC As String
    Public asppID_U_RECURSO As Integer
    Public asppD_U_RECURSO As String
    Public asppREALIZADA As Boolean
    Public asppID_R_SOL As Integer
    Public asppD_R_SOL As String
    Public asppOBSERVACIONES As String
    Public asppID_ESTADO_R As Integer
    'VISTA SOL_MAESTRO DE SOLICITANTES DOCUMENTOS
    Public dID_D_R As Integer
    Public dID_S As Integer
    Public dID_T_DOC_ASP As Integer
    Public dD_T_DOC_ASP As String
    Public dRECEPCIONADO As Boolean
    Public dOBSERVACIONES As String
    'VISTA MAESTRO DE DOCUMENTOS DIGITALES ASPIRANTES
    Public ddaID_M_DD_A As Integer
    Public ddaID_S As Integer
    Public ddaID_D1 As Integer
    Public ddaDIRECTORIO As String
    Public ddaID_T_DOC_ASP As Integer
    Public ddaD_T_DOC_ASP As String
    Public ddaNOMBRE As String
    Public ddaOBSERVACION As String
    'VISTA MAESTRO DE PERSONAL TERCERIZADO
    Public ptID_P_T As Integer
    Public ptID_E_T As Integer
    Public ptD_E_T As String
    Public ptCODIGO As String
    Public ptAPELLIDOS As String
    Public ptNOMBRES As String
    Public ptAN As String
    Public ptN_CEDULA As String
    Public ptID_T_SEXO As Integer
    Public ptD_T_SEXO As String
    Public ptTELEFONO_1 As String
    Public ptTELEFONO_2 As String
    Public ptD_CARGO_ES As String
    Public ptID_ESTADO_P As Integer
    Public ptD_ESTADO_P As String
    Public ptDIRECCION As String
    Public ptNSS As String
    Public ptOBSERVACIONES As String
    Public ptF_INGRESO As String
    Public ptF_BAJA As String
    Public ptCAUSA_RETIRO As String
    'VISTA MAESTRO DE HIGIENE_DATOS DEL TRABAJADOR
    Public h1ID_M_IT As Integer
    Public h1ID_M_P As Integer
    Public h1CODIGO As String
    Public h1NO_PARTE_ACC As String
    Public h1NSS As String
    Public h1NO_REP_NSS As String
    Public h1NO_REP_MITRAB As String
    Public h1N_CEDULA As String
    Public h1APELLIDOS As String
    Public h1NOMBRES As String
    Public h1EDAD As Integer
    Public h1ID_T_SEXO As Integer
    Public h1D_T_SEXO As String
    Public h1ID_T_HORARIO As Integer
    Public h1D_T_HORARIO As String
    Public h1ACCIDENTE_ANTERIOR As String
    Public h1CARGO As String
    Public h1DEPARTAMENTO As String
    Public h1SERVICIO As String
    Public h1ANT_EMPRESA_MESES As Integer
    Public h1ANT_PUESTO_MESES As Integer
    Public h1ID_ESTADO_P As Integer
    Public h1D_ESTADO_P As String
    'VISTA MAESTRO DE HIGIENE INFORMACION DEL ACCIDENTE
    Public h2ID_M_IT As Integer
    Public h2ID_M_P As Integer
    Public h2NO_PARTE_ACC As String
    Public h2NO_REP_NSS As String
    Public h2NO_REP_MITRAB As String
    Public h2EDAD As Integer
    Public h2ACCIDENTE_ANTERIOR As String
    Public h2DEPARTAMENTO As String
    Public h2SERVICIO As String
    Public h2CARGO As String
    Public h2ANT_EMPRESA_MESES As Integer
    Public h2ANT_PUESTO_MESES As Integer
    'VISTA MAESTRO DE HIGIENE DATOS DEL EVENTO
    Public mieID_M_EVENTO As Integer
    Public mieID_M_IT As Integer
    Public mieID_M_P As Integer
    Public mieDESCRIPCION_ACC As String
    Public mieID_T_ACCIDENTE As Integer
    Public mieD_T_ACCIDENTE As String
    Public mieLUGAR_ACC As String
    Public mieFECHA_ACC As String
    Public mieHORA_ACC As String
    Public mieFECHA_REPORTE As String
    Public mieHORA_REPORTE As String
    Public mieHORAS_LABORADAS As Double
    Public mieHORAS_PERDIDAS As Double
    Public mieID_AMG As Integer
    Public mieD_AMG As String
    Public mieID_AMSE As Integer
    Public mieD_AMSE As String
    Public mieID_FO As Integer
    Public mieD_FO As String
    Public mieID_PCL As Integer
    Public mieD_PCL As String
    Public mieID_NL As Integer
    Public mieD_NL As String
    Public mieDIAS_SUBSIDIO As Integer
    Public mieDECLARACION_T1 As String
    Public mieDECLARACION_T2 As String

    Public mieLUGAR_E_ACC As String
    Public miePCL_E As String
    Public mieTIEMPO_O As String
    Public mieMES As String
    Public mieF_II As String
    Public mieFCI As String
    Public mieACC_ANT As String
    Public mieTURNO_DE_T As String
    Public mieHAL As String
    Public mieSDT As String
    Public mieLQR As String
    Public mieENTREVISTADO_1 As String
    Public mieENTREVISTADO_2 As String

    'VISTA MAESTRO DE HIGIENE CAUSAS FACTORES Y GRAVEDAD
    Public h3ID_CFG As Integer
    Public h3ID_M_IT As Integer
    Public h3ID_M_P As Integer
    Public h3ID_OSP As Integer
    Public h3D_OSP As String
    Public h3ID_FP As Integer
    Public h3D_FP As String
    Public h3ID_FT As Integer
    Public h3D_FT As String
    Public h3ID_AI As Integer
    Public h3D_AI As String
    Public h3ID_CI As Integer
    Public h3D_CI As String
    Public h3ID_FR As Integer
    Public h3D_FR As String
    Public h3ID_NG As Integer
    Public h3D_NG As String
    Public h3FG As String
    Public h3FSE As String
    Public h3RACC As String
    Public h3NLG As String
    Public h3AC As String
    Public h3NG As String
    Public h3SUBS As String

    'VISTA MAESTRO DE HIGIENE DISPOSICION FINAL Y ANEXOS
    Public h4ID_DFA As Integer
    Public h4ID_M_IT As Integer
    Public h4ID_M_P As Integer
    Public h4ID_AMC As Integer
    Public h4D_AMC As String
    Public h4CONCLUSIONES As String
    Public h4LYN As String
    Public h4NO_REG_ADMI_E As String
    Public h4NO_RES_CLI As String
    '-
    Public h4RC As String
    Public h4AMC As String
    Public h4AMCMA As String
    Public h4RT As String
    Public h4OBS As String
    Public h4ANEXOS As String
    'VISTA MAESTRO DE HIGIENE DOSIMETRIA
    Public h5ID_DOS As Integer
    Public h5DEPARTAMENTO As String
    Public h5SERVICIO As String
    Public h5CARGO As String
    Public h5ID_M_P As Integer
    Public h5CODIGO_DOSIMETRO As String
    Public h5FECHA_LECTURA As String
    Public h5FECHA_PE_I As String
    Public h5FECHA_PE_F As String
    Public h5DOSIS_EP As String
    Public h5DOSIS_APS As String
    Public h5DOSIS_ASS As String
    Public h5DOSIS_AA As String
    Public h5FECHA_I_PORTADOR As String
    Public h5FECHA_C_PROGRAMADA As String
    Public h5ID_PER_DOSIME As Integer
    Public h5D_PER_DOSIME As String
    Public h5OBSERVACION As String
    'VISTA MAESTRO DE HIGIENE EXAMEN MEDICO OCUPACIONAL
    Public emoID_EMO As Integer
    Public emoDEPARTAMENTO As String
    Public emoSERVICIO As String
    Public emoCARGO As String
    Public emoID_M_P As Integer
    Public emoFECHA_EVA As String
    Public emoNO_EXPEDIENTE As String
    Public emoID_T_EVALUACION As Integer
    Public emoD_T_EVALUACION As String
    Public emoCARGO_ANTERIOR As String
    Public emoCARGO_ACTUAL As String
    Public emoAE_ANTERIOR As String
    Public emoAE_ACTUAL As String
    Public emoDIAGNOSTICO As String
    Public emoRECOMENDACIONES As String
    Public emoID_R_EVALUACION As Integer
    Public emoD_R_EVALUACION As String
    Public emoOBSERVACIONES As String
    'VISTA MAESTRO DE HIGIENE EXAMEN MEDICO OCUPACIONAL EXAMENES
    Public exID_EX As Integer
    Public exID_EMO As Integer
    Public exID_T_EXAMENES As Integer
    Public exD_T_EXAMENES As String
    Public exID_TRE As Integer
    Public exD_TRE As String
    Public exOBSERVACIONES As String
    'VISTA MAESTRO DE BECADOS
    Public mbID_B As Integer
    Public mbID_M_P As Integer
    Public mbNOMBRES As String
    Public mbAPELLIDOS As String
    Public mbCODIGO As String
    Public mbN_CEDULA As String
    Public mbN_MINSA As String
    Public mbD_T_SEXO As String
    Public mbNOMBRE_ESTUDIO As String
    Public mbID_PAIS As Integer
    Public mbD_PAIS As String
    Public mbCENTRO_ESTUDIO As String
    Public mbFEC_INI As String
    Public mbFEC_FIN As String
    Public mbTELEFONO As String
    Public mbNO_CUENTA As String
    Public mbCORREO As String
    Public mbMATRICULA As String
    Public mbINSCRIPCION As String
    Public mbALIMENTACION As String
    Public mbHOSPEDAJE As String
    Public mbPAGO_TITULO As String
    Public mbOTROS As String
    Public mbTOTAL As String
    Public mbOBSERVACIONES As String
    '////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    '////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    'EXPEDIENTES
    'VISTA MAESTRO DE NUCLEO FAMILIAR
    Public vmnfID_NF As Integer
    Public vmnfID_M_P As Integer
    Public vmnfID_PARENTELA As Integer
    Public vmnfD_PARENTELA As String
    Public vmnfAPELLIDOS_NOMBRES As String
    Public vmnfID_T_SEXO As Integer
    Public vmnfD_T_SEXO As String
    Public vmnfFEC_NAC As String
    Public vmnfEDAD As String
    Public vmnfID_N_ACADEMICO As Integer
    Public vmnfD_N_ACADEMICO As String
    Public vmnfDIRECCION_D As String
    Public vmnfTELEFONO_1 As String
    Public vmnfTELEFONO_2 As String
    Public vmnfLUGAR_T As String
    Public vmnfDIRECCION_T As String
    Public vmnfCARGO_T As String
    Public vmnfFALLECIDO As String
    'MAESTRO DE EXPERIENCIA LABORAL
    Public vmelID_EL As Integer
    Public vmelID_M_P As Integer
    Public vmelEMPRESA_NOMBRE As String
    Public vmelEMPRESA_DIRECCION As String
    Public vmelEMPRESA_TELEFONO As String
    Public vmelEMPRESA_ACTIVIDAD As String
    Public vmelCARGO_DESEM As String
    Public vmelJEFE_INMEDIATO As String
    Public vmelSALARIO As String
    Public vmelFEC_INI As String
    Public vmelFEC_FIN As String
    Public vmelCAUSA_RETIRO As String
    Public vmelOBLI_RESP As String
    'MAESTRO DE REFERENCIAS PERSONALES
    Public vmrID_RP As Integer
    Public vmrID_M_P As Integer
    Public vmrAPELLIDOS_NOMBRES As String
    Public vmrDIRECCION As String
    Public vmrOCUPACION As String
    Public vmrTELEFONO As String
    'VISTA MAESTRO DE ESTUDIOS
    Public vmesID_M_EST As Integer
    Public vmesID_M_P As Integer
    Public vmesID_T_ESTUDIO As Integer
    Public vmesD_T_ESTUDIO As String
    Public vmesID_E_MED As Integer
    Public vmesD_E_MED As String
    Public vmesULT_GRADO_A As String
    Public vmesFECHA_ESTUDIO As String
    Public vmesNOMBRE_ESTUDIO As String
    Public vmesNOMBRE_C_ESTUDIO As String
    Public vmesDIRECC_C_ESTUDIO As String
    Public vmesESTUDIO_F_PAIS As Boolean
    Public vmesID_PAIS As Integer
    Public vmesD_PAIS As String
    Public vmesTITULO_OBT As String
    Public vmesOBSERVACIONES As String
    'VISTA MAESTRO DE HABILIDADES ADMIN
    Public vmhID_H_ADMIN As Integer
    Public vmhID_M_P As Integer
    Public vmhID_HABILIDAD As Integer
    Public vmhD_HABILIDAD As String
    Public vmhPORCENTAJE As String
    Public vmhOBSERVACIONES As String
    'VISTA MAESTRO DE IDIOMAS
    Public vmiID_M_I As Integer
    Public vmiID_M_P As Integer
    Public vmiID_IDIOMA As Integer
    Public vmiD_IDIOMA As String
    Public vmiHABLA As Boolean
    Public vmiP_HABLA As String
    Public vmiLEE As Boolean
    Public vmiPORCENTAJE_L As String
    Public vmiESCRIBE As Boolean
    Public vmiPORCENTAJE_E As String
    Public vmiOBSERVACIONES As String
    'VISTA MAESTRO DE CURVA Y TALLA
    Public vmcytID_CT As Integer
    Public vmcytID_M_P As Integer
    Public vmcytID_T_CT As Integer
    Public vmcytD_T_CT As String
    Public vmcytTALLA As String
    Public vmcytOBSERVACIONES As String
    'VISTA MAESTRO DE CLASIFICACION DE PERSONAL
    Public vmcoID_C_PERSONAL As Integer
    Public vmcoID_M_P As Integer
    Public vmcoID_C_PE As Integer
    Public vmcoD_C_PE As String
    Public vmcoOBSERVACIONES As String
    'VISTA MAESTRO DE CONDECORACIONES
    Public vmcID_C_CONDE As Integer
    Public vmcD_C_CONDE As String
    Public vmcID_CONDE As Integer
    Public vmcCODIGO As String
    Public vmcD_CONDE As String
    Public vmcID_M_CONDE As Integer
    Public vmcID_M_P As Integer
    Public vmcCONDE_A As String
    Public vmcMOTIVOS As String
    Public vmcOBSERVACIONES As String
    'VISTA MAESTRO DE EVENTUALIDADES
    Public vmeID_M_EV As Integer
    Public vmeID_M_P As Integer
    Public vmeD_N1 As String
    Public vmeD_N2 As String
    Public vmeJEFE As String
    Public vmeFEC_EVE As String
    Public vmeID_CR_EVENTOS As Integer
    Public vmeD_CR_EVENTOS As String
    Public vmeID_E As Integer
    Public vmeD_E As String
    Public vmeEVENTUALIDAD As String
    'VISTA MAESTRO DE NOMINAS Y SALARIOS
    Public vmnsID_M_NYS As Integer
    Public vmnsID_M_P As Integer
    Public vmnsID_MOVIMIENTO_N As Integer
    Public vmnsD_MOVIMIENTO_N As String
    Public vmnsF_MOVIMIENTO_N As String
    Public vmnsID_NOMINA As Integer
    Public vmnsD_NOMINA As String
    Public vmnsPROPUESTA As String
    Public vmnsSALARIO As String
    Public vmnsSAL_MINIMO As String
    Public vmnsOBSERVACIONES As String
    Public vmnsACTIVO As Boolean
    'VISTA MAESTRO DE DOCUMENTOS DIGITALES
    Public vmdID_M_DD As Integer
    Public vmdID_M_P As Integer
    Public vmdID_M_C As Integer
    Public vmdID_D1 As Integer
    Public vmdDIRECTORIO As String
    Public vmdID_T_DOC As Integer
    Public vmdD_T_DOC As String
    Public vmdNOMBRE As String
    Public vmdOBSERVACION As String
    'VISTA HISTORICO DE MOVIMIENTO 
    Public vID_HIST_M As Integer
    '
    Public hmID_HIST_M As Integer
    Public hmFEC_ING_PAME As String
    Public hmID_M_P As Integer
    Public hmCODIGO As String
    Public hmAN As String
    Public hmFEC_MOV As String
    Public hmFEC_APLICA As String
    Public hmID_T_M_EXP As Integer
    Public hmD_T_M_EXP As String
    Public hmID_ST_M_L_EXP As Integer
    Public hmD_ST_M_L_EXP As String
    Public hmID_ST_M_R_EXP As Integer
    Public hmD_ST_M_R_EXP As String
    Public hmD_CARGO_ES As String
    Public hmD_GP As String
    Public hmD_GR As String
    Public hmD_N1 As String
    Public hmD_N2 As String
    Public hmD_N3 As String
    Public hmD_N4 As String
    Public hmD_N5 As String
    Public hmD_N6 As String
    Public hmD_N7 As String
    Public hmD_N8 As String
    Public hmN_ORDEN As String
    Public hmD_NOMINA As String
    Public hmSALARIO As String
    Public hmDETALLE As String
    Public hmMIXTA As String
    Public hmMILITAR As String
    Public hmPAME As String
    Public hmAPLICAR As String
    Public hmESTADISTICO As String
    Public hmUSUARIO_ACT As String
    Public hmFECHA_ACT As String
    Public hmD_ADMIN As String
    'VISTA VISTA MAESTRO DE HORARIOS
    Public vmhiID_H As Integer
    Public vmhiID_M_P As Integer
    Public vmhiID_T_HORARIO As Integer
    Public vmhiD_T_HORARIO As String
    Public vmhiHORA_E As String
    Public vmhiHORA_S As String
    Public vmhiCHRT As Integer
    'VISTA MAESTRO DE CONTRATOS Y EVALUACIONES
    Public mcyeID_M_CYE As Integer
    Public mcyeID_M_P As Integer
    Public mcyeCODIGO As String
    Public mcyeFEC_ING_PAME As String
    Public mcyeID_CONT As Integer
    Public mcyeDESCRIPCION As String
    Public mcyeFECHA_I As String
    Public mcyeFECHA_F As String
    Public mcyeFIRMADO As Boolean
    Public mcyeFECHA_EVA As String
    Public mcyePROMEDIO_NOTA As String
    Public mcyeID_C_E As Integer
    Public mcyeD_C_E As String
    Public mcyeOBSERVACIONES As String
    'VISTA MAESTRO DE SUBSIDIOS
    Public vmssID_SUBS As Integer
    Public vmssID_M_P As Integer
    Public vmssNO_EXPEDIENTE As String
    Public vmssNO_BOLETA As String
    Public vmssID_T_SUBS As Integer
    Public vmssD_T_SUBS As String
    Public vmssN_ORDEN As String
    Public vmssFECHA_I As String
    Public vmssFECHA_F As String
    Public vmssCANT_DIAS As Integer
    Public vmssFECHA_PARTO As String
    Public vmssFECHA_PARTO_PROB As String
    Public vmssFECHA_ACC_LAB As String
    Public vmssFECHA_DECLARACION As String
    Public vmssVALOR_X_DIA As String
    Public vmssVALOR_TOTAL As String
    Public vmssMEDICO As String
    Public vmssN_MINSA As String
    Public vmssID_E_MED As Integer
    Public vmssD_E_MED As String
    Public vmssDIAGNOSTICO As String
    Public vmssOBSERVACIONES As String
    'VISTA MAESTRO DE SITUACION DE PERSONAL
    Public msID As Integer
    Public msNIVEL1 As String
    Public msNIVEL2 As String
    Public msNIVEL3 As String
    Public msNIVEL4 As String
    Public msNIVEL5 As String
    Public msORD As String
    Public msID_M_A As Integer
    Public msID_M_P As Integer
    Public msCODIGO As String
    Public msDIAL As String
    Public msDIA As String
    Public msID_T_SIT_P As Integer
    Public msD_T_SIT_P As String
    Public msID_SIT_P As Integer
    Public msD_SIT_P As String
    Public msSIGLA As String
    Public msVALOR_SIT As String
    Public msVALOR_DIA As String
    Public msOBSERVACIONES As String
    Public msDETALLE_1 As String
    Public msDETALLE_2 As String
    Public msDETALLE_3 As String

    Public msD_ADMIN As String
    Public msUSUARIO_ACT As String
    Public msFECHA_ACT As String
    '///////////////////////////////////////////////////////////////////////////////////////
    'VARIABLES PARA MATRIZ BAC
    '///////////////////////////////////////////////////////////////////////////////////////
    'DATOS DEL MAESTRO DE CARGO
    'Public vID_M_P As Integer
    Public vNA As String
    Public vN As String
    Public vA As String
    Public vN1 As String
    Public vN2 As String
    Public vNi1 As String
    Public vNi2 As String
    Public vNi3 As String
    Public vNi4 As String
    Public vNi5 As String
    Public vNi6 As String
    Public vNi7 As String
    Public vNi8 As String
    Public vA1 As String
    Public vA2 As String
    Public vREFERENCIA As String
    Public vOCUPACION As String
    Public bacN1 As String
    Public bacN2 As String
    Public bacN3 As String
    Public bacN4 As String
    Public bacN5 As String
    Public bacN6 As String
    Public bacN7 As String
    Public bacN8 As String
    Public vGRADO As String
    Public vMILITAR As Boolean
    Public vPAME As Boolean
    Public vJEFE As Boolean
    Public vORDEN_ESTRUCTURA As Integer
    'DATOS DE EMPLEADO
    Public vSEXO As String
    Public vESTADO_CIVIL As String
    Public vPROFESION_OFICIO As String
    Public vFECHA_INGRESO As String
    Public vBENEFICIARIO As String
    Public vFECHA_NACIMIENTO As String
    Public vPAIS_NACIMIENTO As String
    Public vNACIONALIDAD As String
    Public vPAIS_RESIDENCIA As String
    Public vDIRECCION_DOMICILIAR As String
    Public vMUNICIPIO_DOMICILIAR As String
    Public vDEPARTAMENTO_DOMICILIAR As String
    Public vTELEFONO As String
    Public vCELULAR As String
    Public vCORREO_ELECTRONICO As String
    Public vTIPO_IDENTIFICACION As String
    Public vCUENTA_BANCO As String
    Public vNA_BENEFICIARIO As String
    Public vPAIS_EMISION_ID As String
    Public vFEC_EMISION_ID As String
    Public vFEC_VENCIMIENTO_ID As String
    Public vID As String
    'DATOS DEL NUCLEO
    Public vCONYUGE As String
    'Public vAPELLIDOS_CONYUGE As String
    Public vCELULAR_CONYUGE As String
    Public vCANT_DEPENDIENTES As Integer
    'DATOS SALARIALES
    Public vINGRESO As String
    '///////////////////////////////////////////////////////////////////////////////////////
    '///////////////////////////////////////////////////////////////////////////////////////
    '///////////////////////////////////////////////////////////////////////////////////////
    'SIE VISTA MAESTRO DE CONSULTA PRINCIPAL
    Public vTIPO As String
    Public vTIPO_INGRESO As String
    Public vNSS As String
    Public vNOMBRES As String
    Public vAPELLIDOS As String
    Public vNOMBRES_Y_APELLIDOS As String
    Public vIDENTIDAD As String
    'Public vSEXO As String
    'Public vGRADO As String
    Public vTIPO_PARENTELA As String
    Public vUM As String
    Public vCARGO As String
    Public vNO_EXPEDIENTE_DPC As String
    Public vCLASIFICACION As String
    Public vCEDULA As String
    Public vNO_CARNE As String
    Public vF_INGRESO As String
    Public vEDAD As String
    Public F_NACIMIENTO As String
    'VISTA MAESTRO DE INMUNIZACIONES
    Public inID_M_INM As Integer
    Public inID_M_P As Integer
    Public inID_VACUNA As Integer
    Public inD_VACUNA As String
    Public inID_DOSIS As Integer
    Public inD_DOSIS As String
    Public inFECHA_V As String
    'VISTA MAESTRO DE PROYECCION
    Public proyID_PROY As Integer
    Public proyID_M_P As Integer
    Public proyID_SIT_P As Integer
    Public proyD_SIT_P As String
    Public proyFECHA_PROY As String
    Public proyOBSERVACIONES As String
End Module
